---
root: 
permalink: /:year/:month/:day/:title
lsi: false
pygments: true

# Site configuration
url:          http://blog.apiary.io
title:        The Apiary Blog
description:  Updates on everyone's favourite REST API tools company
authors:
  netmilk:
    name: Adam Kliment
    display_name: netmilk
    email: "adam@apiary.io"
    twitter: "ntmlk"
  zdenek:
    name: Zdenek Nemec
    display_name: Z
    email: "z@apiary.io"
    twitter: "zdne"
  lukas:
    name: Lukas Linhart
    display_name: Lukas Linhart
    email: "lukas@apiary.io"
    twitter: "almadcz"
  jakub:
    name: Jakub Nesetril
    display_name: Jakub Nesetril
    email: "jakub@apiary.io"
    twitter: "jakubnesetril"
    
keywords:     rest, api, tools, json, debugging, proxy, documentation, testing, tests, support
author:       Apiary
email:        jakub@apiary.io
static: "https://apiary-static.s3.amazonaws.com/appstatic"
version: 1338364425
menu:
  - ['http://apiary.io/how-it-works', 'How It Works']
  - ['http://blog.apiary.io/', 'Blog']
  - ['http://apiary.io/company', 'Company']
  - ['https://login.apiary.io/login', 'Sign In']
tracking: >
  <script>
   var _gaq = [['_setAccount', 'UA-18252923-1'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>