---
root:
permalink: /:year/:month/:day/:title
lsi: false
highlights: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-redirect-from

# Site configuration
url:          http://blog.apiary.io
title:        The Apiary Blog
description:  Updates on everyone's favourite REST API tools company
authors:
  netmilk:
    name: Adam Kliment
    display_name: netmilk
    email: "adam@apiary.io"
    twitter: "ntmlk"
  zdenek:
    name: Zdenek Nemec
    display_name: Z
    email: "z@apiary.io"
    twitter: "zdne"
  lukas:
    name: Lukas Linhart
    display_name: Lukas Linhart
    email: "lukas@apiary.io"
    twitter: "almadcz"
  jakub:
    name: Jakub Nesetril
    display_name: Jakub Nesetril
    email: "jakub@apiary.io"
    twitter: "jakubnesetril"
  jan:
    name: Jan Moravec
    display_name: Jan Moravec
    email: "jan@apiary.io"
    twitter: "janmoravec"
  neha:
    name: Neha Sondhi
    display_name: Neha Sondhi
    email: "neha@apiary.io"
    twitter: "NSondhi5"
  mark:
    name: Mark W. Foster
    display_name: Mark W. Foster
    email: "mark@apiary.io"
    twitter: "fosrias"
  nick:
    name: Nick Barnwell
    display_name: Nick Barnwell
    email: "nib@microsoft.com"
    twitter: "@nickbarnwell"
  stephen:
    name: Stephen Mizell
    display_name: Stephen Mizell
    email: "stephen@apiary.io"
    twitter: "Stephen_Mizell"
  andrew:
    name: Andrew Brown
    display_name: Andrew Brown
    email: "andrew@apiary.io"
    twitter: "@uberdru"
  kyle:
    name: Kyle Fuller
    display_name: Kyle
    email: "kyle@apiary.io"
    twitter: "@kylefuller"
  frantisek:
    name: František Hába
    display_name: František
    email: "frantisek@apiary.io"
    twitter: "@Baggz"

keywords:     rest, api, tools, json, debugging, proxy, documentation, testing, tests, support
author:       Apiary
email:        jakub@apiary.io
static: "https://apiary-static.s3.amazonaws.com/assets"
# static: "https://static.apiary.dev:9000"
version: 1338364425
menu:
  - ['https://apiary.io/how-it-works', 'How It Works']
  - ['https://apiary.io/pricing', 'Pricing']
  - ['https://apiary.io/products', 'Product']
  - ['http://blog.apiary.io/', 'Blog']
  - ['https://apiary.io/company', 'Company']
  - ['https://login.apiary.io/login', 'Sign In']
tracking: >
  <script>
   var _gaq = [['_setAccount', 'UA-18252923-1'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
