---
root:
permalink: /:title
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
highlights: true
highlighter: rouge
timezone: UTC # To match it with Circle CI default settings
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
exclude: ['Gemfile*', 'vendor', 'README.md', 'Rakefile', 'docker']

# Site configuration
url:          https://blog.apiary.io
title:        The Apiary Blog
description:  Updates on everyone's favourite REST API tools company
authors:
  netmilk:
    name: Adam Kliment
    display_name: netmilk
    email: "adam@apiary.io"
    twitter: "ntmlk"
  zdenek:
    name: Zdenek Nemec
    display_name: Z
    email: "z@apiary.io"
    twitter: "zdne"
  lukas:
    name: Lukas Linhart
    display_name: Lukas Linhart
    email: "lukas@apiary.io"
    twitter: "almadcz"
  jakub:
    name: Jakub Nesetril
    display_name: Jakub Nesetril
    email: "jakub@apiary.io"
    twitter: "jakubnesetril"
  jan:
    name: Jan Moravec
    display_name: Jan Moravec
    email: "jan@apiary.io"
    twitter: "janmoravec"
  neha:
    name: Neha Sondhi
    display_name: Neha Sondhi
    email: "neha@apiary.io"
    twitter: "NSondhi5"
  mark:
    name: Mark W. Foster
    display_name: Mark W. Foster
    email: "mark@apiary.io"
    twitter: "fosrias"
  nick:
    name: Nick Barnwell
    display_name: Nick Barnwell
    email: "nib@microsoft.com"
  stephen:
    name: Stephen Mizell
    display_name: Stephen Mizell
    email: "stephen@apiary.io"
    twitter: "Stephen_Mizell"
  andrew:
    name: Andrew Brown
    display_name: Andrew Brown
    email: "andrew@apiary.io"
    twitter: "@uberdru"
  kyle:
    name: Kyle Fuller
    display_name: Kyle
    email: "kyle.fuller@oracle.com"
    twitter: "@kylefuller"
  char0n:
    name: Vladimír Gorej
    display_name: char0n
    email: "vladimir.gorej@oracle.com"
    twitter: "@vladimirgorej"
  frantisek:
    name: František Hába
    display_name: František
    email: "frantisek@apiary.io"
    twitter: "@Baggz"
  vincenzo:
    name: Vincenzo Chianese
    display_name: Vincenzo
    email: "vincenzo@apiary.io"
    twitter: "@D3DVincent"
  corvax:
    name: Jakub Mikulas
    display_name: Corvax
    email: "corvax@apiary.io"
    twitter: "@jedenbod"
  dave:
    name: Dave Goldberg
    display_name: Dave Goldberg
    email: "dave.golberg@capitalone.com"
    twitter: "@davidgoldberg"
  davita:
    name: Davita Strong
    display_name: Davita Strong
    email: "davita@apiary.io"
  honza:
    name: Honza Javorek
    display_name: Honza Javorek
    email: "honza@apiary.io"
    twitter: "@honzajavorek"
  daria:
    name: Daria Grudzien
    display_name: Daria Grudzien
    email: "daria.grudzien@oracle.com"
    twitter: "@dariagrudzien"


keywords:     rest, api, tools, json, debugging, proxy, documentation, testing, tests, support
author:       Apiary
email:        jakub@apiary.io
static: "https://static.apiary.io/assets"
version: 1338364425
menu:
  - ['https://apiary.io/how-it-works', 'How It Works']
  - ['https://apiary.io/plans', 'Plans']
  - ['https://apiary.io/products', 'Product']
  - ['https://help.apiary.io/', 'Help']
  - ['https://apiary.io/company', 'Company']
  - ['https://login.apiary.io/login', 'Sign In']
tracking: >
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-18252923-10', 'auto');
    ga('send', 'pageview');
  </script>
