version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle
      - run: bundle exec rake test
  deploy:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle
      - run: ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
